version: "3.7"
services:
    # imagem micro 01
    spotify_api_integration:
        build:
            args:
                user: gabriel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_spotify_api_integration
            - queue
        networks:
            - network-application

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - network-application

    # mysql micro 01
    db_spotify_api_integration:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - network-application

    # queue micro 01
    queue:
        build:
            args:
                user: gabriel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis_spotify_api_integration
        networks:
            - network-application

    #redis
    redis_spotify_api_integration:
        image: redis:latest
        networks:
            - network-application

networks:
    network-application:
        driver: bridge
